apiVersion: v1
kind: Pod
metadata:
  name: kubectl-flame-debug
  namespace: kube-system
spec:
  hostNetwork: true
  hostPID: true
  tolerations:
    - key: "node.cloudprovider.kubernetes.io/uninitialized"
      operator: "Exists"
      effect: "NoSchedule"
  restartPolicy: Never
  containers:
    - name: flame
      image: verizondigital/kubectl-flame:v0.2.4-perf
      securityContext:
        privileged: true
      command: ["/bin/sh", "-c", "sleep 1d"]
      volumeMounts:
        - name: proc
          mountPath: /host/proc
        - name: sys
          mountPath: /host/sys
        - name: tmp
          mountPath: /tmp
  volumes:
    - name: proc
      hostPath:
        path: /proc
    - name: sys
      hostPath:
        path: /sys
    - name: tmp
      hostPath:
        path: /tmp
